### ISSUE TITLE
get_value method returns nothing if the requested key does not exist

### ISSUE THREAD

**Issue by fieteboerner** [perl-ldap/perl-ldap#46]
Today I faced an issue by requesting a value by calling `$entry->get_value('optional_attribute_key')` and try to put it directly in a hash/hashref like:

``` perl
my $data = (
    ...
    'key' => $entry->get_value('optional_attribute_key'),
    ...
);
```

perl throws `Odd number of elements in hash assignment at ...`

The problem is that the whole hash is broken and returns mixed invalid values.

I have researched your library and have found this line: [Entry.pm:130](https://github.com/perl-ldap/perl-ldap/blob/master/lib/Net/LDAP/Entry.pm#L130)
The function returns `nothing` and not as expected `undef` like it is written in the [documentation](https://metacpan.org/pod/Net::LDAP::Entry#get_value-ATTR-OPTIONS). so it seems to be a bug.

**Comment by marschap** [comment]
Hi & sorry for the late reply,

and again sorry for rejecting this issue.
This is what the _perlfunc_ manual page states about _return_ without argument: "_If no EXPR is given, returns an empty list in list context, the undefined value in scalar context, and (of course) nothing at all in void context._"
I.e. get_value() conforms to its documentation.

I see the issue more in cour code: it blindly assumes scalar mode, while - in reality - it is in list mode.
Better use
`'key' => [ $entry->get_value('optional_attribute_key') ],`
to also be able to deal with cases when get_value returns more than exactly one value.
